# Generated by Django 2.1.2 on 2018-12-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hole',
            name='round',
        ),
        migrations.AddField(
            model_name='hole',
            name='rounds',
            field=models.ManyToManyField(to='courses.Round'),
        ),
    ]
