# Generated by Django 2.1.2 on 2018-12-22 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20181222_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holeroundlink',
            name='hole',
        ),
        migrations.RemoveField(
            model_name='holeroundlink',
            name='round',
        ),
        migrations.DeleteModel(
            name='HoleRoundLink',
        ),
    ]
