# Generated by Django 2.1.2 on 2018-12-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20181222_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='COURSE NAME', max_length=255),
        ),
    ]
