# Generated by Django 2.1.2 on 2018-12-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hole',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
