# Generated by Django 2.1.2 on 2018-12-22 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_hole_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hole',
            name='rounds',
        ),
        migrations.AddField(
            model_name='round',
            name='holes',
            field=models.ManyToManyField(to='courses.Hole'),
        ),
    ]
