# Generated by Django 2.1.2 on 2018-12-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('scorecards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scorecardlink',
            name='scorecard',
        ),
        migrations.RemoveField(
            model_name='scorecardlink',
            name='user',
        ),
        migrations.AddField(
            model_name='scorecard',
            name='users',
            field=models.ManyToManyField(to='users.Profile'),
        ),
        migrations.DeleteModel(
            name='ScorecardLink',
        ),
    ]
